<?php

namespace Zeal\Paymob;

use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class PaymobServiceProvider extends PackageServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->mergeConfigFrom(
            __DIR__ . '/../config/paymob.php',
            'paymob'
        );
    }

    public function configurePackage(Package $package): void
    {
        $package
            ->name('paymob')
            ->hasConfigFile('paymob');
    }
}
